# Generated by Django 2.0.6 on 2019-05-10 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoshift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.DateTimeField(verbose_name='班车时间')),
                ('duration', models.CharField(max_length=40, verbose_name='时长')),
                ('path', models.PositiveIntegerField(choices=[(1, '兰溪校区-校本部'), (2, '校本部-兰溪校区'), (3, '兰溪-金华-校本部'), (4, '兰溪-金华')], default=1, verbose_name='路线')),
            ],
            options={
                'verbose_name': '汽车班次',
                'verbose_name_plural': '汽车班次',
                'ordering': ['times'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=20, verbose_name='车牌号')),
                ('driver', models.CharField(max_length=10, verbose_name='驾驶员')),
                ('driver_phone', models.CharField(max_length=15, verbose_name='驾驶员电话')),
                ('set_num', models.IntegerField(verbose_name='座位数')),
                ('price', models.FloatField(max_length=10, verbose_name='价格')),
                ('notice', models.TextField(verbose_name='公告')),
                ('car_type', models.PositiveIntegerField(choices=[(1, '普通校车'), (2, '教师用车')], default=1, verbose_name='用车类型')),
            ],
        ),
        migrations.CreateModel(
            name='CarAndShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('due_num', models.IntegerField(verbose_name='预约人数')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Autoshift')),
            ],
        ),
    ]
