# Generated by Django 2.0.6 on 2019-05-10 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carandshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoshift',
            name='car',
            field=models.ManyToManyField(to='car.Car'),
        ),
        migrations.AddField(
            model_name='autoshift',
            name='user',
            field=models.ManyToManyField(through='car.CarAndShift', to=settings.AUTH_USER_MODEL),
        ),
    ]
