# Generated by Django 2.0.6 on 2019-05-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20190510_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': '校车', 'verbose_name_plural': '校车'},
        ),
        migrations.AlterModelOptions(
            name='carandshift',
            options={'verbose_name': '用户约车', 'verbose_name_plural': '用户约车'},
        ),
    ]
