# Generated by Django 2.0.6 on 2019-05-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20190510_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(max_length=20, verbose_name='路径名')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
            },
        ),
        migrations.AlterField(
            model_name='autoshift',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.PathType'),
        ),
    ]
