# Generated by Django 2.0.6 on 2019-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20190511_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_state',
            field=models.PositiveIntegerField(choices=[(1, '正常发车'), (2, '人数太少不发车')], default=1, verbose_name='用车状态'),
        ),
    ]
