# Generated by Django 2.0.6 on 2019-05-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.PositiveIntegerField(choices=[(1, '普通学生'), (2, '学生干部'), (3, '职工')], default=1, verbose_name='身份'),
        ),
    ]
